# Tells Spring to use the Environment Variable you set in Render
spring.datasource.url=${DATABASE_URL}

# Tells Hibernate to automatically create your tables in Supabase
spring.jpa.hibernate.ddl-auto=update

# Tells Hibernate to speak PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Suppress a common Spring Boot warning
spring.jpa.open-in-view=false
