# This tells Spring Boot to look for Render's Database URL environment variable
spring.datasource.url=${DATABASE_URL}

# This automatically creates your database tables based on your Java Classes
spring.jpa.hibernate.ddl-auto=update

# Tells Hibernate to speak PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Avoids a common warning in the console
spring.jpa.open-in-view=false
